### ISSUE TITLE
make it run on Jupyter Notebook in Python 2.7

### ISSUE THREAD

**Issue by TaiSakuma** [alphatwirl/atpbar#3]
To make it work on Jupter Notebook in Python 2.7
- need ipywidgets 7 and widgetsnbextension 3, https://github.com/jupyter/notebook/issues/2764#issuecomment-339308263
- and enable the widget extension
```bash
jupyter nbextension enable --py widgetsnbextension
```

**Comment by TaiSakuma** [comment]
- the atpbar actually works on Jypter Notebook in Python 2.7
- no change in atpbar was necessary
- just needed to enable the widget extension properly

**Comment by arunasank** [comment]
How do we make it run on python3? : (

**Comment by TaiSakuma** [comment]
It runs on Python 3. This is an old closed thread. The latest version doesn't support Python 2.7.
