### ISSUE TITLE
Console output cut off

### ISSUE THREAD

**Issue by Victorious3** [alphatwirl/atpbar#5]
First of, I'm really impressed by this library and its ability to handle progress bars from multiple processes. 

There's one small issue I'm having, and that's the terminal output.
I'm writing a downloader script and I tried using the name attribute as a way to show the URL its currently downloading. However, this line here:
https://github.com/alphatwirl/atpbar/blob/b3f7c4ea81cbcc65fb7331b1671b7dc513a0da21/atpbar/presentation/bartty.py#L42
makes sure that I never get the url to display properly. I guess its to limit the width to 80 characters. Could you make this behavior configurable? Or better yet, make the progress bar adapt to the terminal width.

**Comment by TaiSakuma** [comment]
Thank you for your suggestion. I will have a look.

**Comment by TaiSakuma** [comment]
I released the version [1.0.4](https://pypi.org/project/atpbar/1.0.4/).
In this release, the name field will not be cut off if the terminal is wide enough.

**Comment by Victorious3** [comment]
Thank you! 
I can't test it right now but I'll come back to you should there be any further issues.
